# Generated by Django 3.0 on 2020-01-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='details',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='landmark',
            name='thumbnail',
            field=models.CharField(default='', max_length=300),
        ),
    ]
