version: "3.7"

services:
  db:
    image: mdillon/postgis:10
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./backend/sql/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    restart: unless-stopped

  backend:
    <<: &backend
      build: backend
      image: backend
      environment:
        - DB_HOST=db
      volumes:
        - ./backend:/app
      depends_on:
        - db
    ports:
      - "3000:3000"

  migration:
    <<: *backend
    command: python manage.py migrate

  frontend:
    build: frontend
    image: frontend
    volumes:
        - ./frontend/:/app
        - /app/node_modules
    ports:
      - "8000:8000"

volumes:
  db-data:
